### ISSUE TITLE
Are you looking for an original Logo for the app?

### ISSUE THREAD

**Issue by SecularSteve** [warren-bank/Android-WebCast#11]
If you are, I offer to make one for free.

I'm asking for permission first because I don't want to do this for nothing.

**Comment by warren-bank** [comment]
That's kind of you to offer, but I'm going to pass for the following reasons:

1. the current icon is also baked into the Chromecast receiver (ie: when the video stops, or errors out)
2. it's just not very important to me.. not worth the time and effort for either of us to bother making changes to it

Thanks again for the generous offer!
But no.
