### ISSUE TITLE
App will force close when trying to load complex websites in an outdated WebView.

### ISSUE THREAD

**Issue by sagorahmed** [warren-bank/Android-WebCast#2]
#### Expected behavior
The users should be able to visit web pages without getting any trouble.

#### Actual behavior
When I visited and tried to open a post, then the app crashed. ```https://steemit.com``` was the website.

#### How to reproduce
1. Open the app
2. Go to ```https://steemit.com```
3. Try to open a post by clicking on it. A few seconds later notice the bug.

* App version: 04.07.01
* Operating system: Android 6.0.1

#### LogCat
All the logs that I produced on my phone.

```
05-21 16:13:49.996  2697  3586 I WindowState: WIN DEATH: Window{787efe1 u0 d0 p17267 com.github.warren_bank.webcast/com.github.warren_bank.webcast.webview.BrowserActivity}

05-21 16:13:49.996  2697  2712 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=95, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@dfcb6c2)

05-21 16:13:49.996  2697  2711 I ActivityManager: Process com.github.warren_bank.webcast (pid 17267)(adj 1) has died(93,304)

05-21 16:13:49.996  2697  3093 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=95, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]

05-21 16:13:49.996  2697  2711 D ActivityManager: cleanUpApplicationRecord -- 17267

05-21 16:13:49.996  2697  3093 D ConnectivityService: sending notification RELEASED for NetworkRequest [ id=95, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]

05-21 16:13:49.996  2697  3590 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=96, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@551cd3)

05-21 16:13:50.006  2697  2711 D ActivityManager: removeProcessNameLocked mProcessNames.remove pid=17267 ,hash=25155352 ,name=com.github.warren_bank.webcast

05-21 16:13:50.006  2697  2711 D ActivityManager: isAutoRunBlockedApp:: com.github.warren_bank.webcast, Auto Run ON
```

**Comment by warren-bank** [comment]
hmm..

Just trying it out on a very low-performance phone that's sitting next to me at the moment.. I can't reproduce this. The site and its posts load fine.

I'll try googling some of the terms in your logcat.. to see if they can give me some clue as to what happened. But ultimately, I don't think that there's really anything I could do if a website was to crash your WebView. I mean.. the WebView is entirely responsible for browsing the web, and it isn't part of this app.. it's a common component that's already on your phone.. and is simply used by this app (as well as by many others).

**Comment by warren-bank** [comment]
I'd be curious to know if the WebView in [this app](https://github.com/warren-bank/Android-WebCast/tree/01-foundation/2-webview/src/main).. which comes from [this article](https://www.journaldev.com/15729/android-webview-bookmarks).. crashes as well.. since it is super bare-bones.. having no functionality beyond a WebView and bookmarks.

[webview-debug.apk.zip](https://github.com/warren-bank/Android-WebCast/files/3202361/webview-debug.apk.zip)

**Comment by sagorahmed** [comment]
Hi @warren-bank 
Don't know why occurring it on that specific site. But this crash confused me as well after I captured using ADB. There are no error logs and no FATAL EXCEPTION about this app in that logcat file. After searching many ways, i found those logs but I don't know those logs are responsible for crash or not.
I think you should try this issue on an android emulator.
I have also replicated this issue in your provided [file](https://github.com/warren-bank/Android-WebCast/files/3202361/webview-debug.apk.zip)

![bug](https://media.giphy.com/media/eKDeCf94Zl2yHrxyAN/giphy.gif)

**Comment by warren-bank** [comment]
hmm..

well, since you're seeing similar crash behavior in that bare-bones app.. then it definitely traces back to the WebView component on your system.

just out of curiousity.. are you using a custom ROM? ..custom WebView component (ex: [Bromite SystemWebView](https://github.com/bromite/bromite/wiki/Installing-SystemWebView))? ..is there anything about your system that would make it potentially unstable?

**Comment by sagorahmed** [comment]
No, I haven't installed custom ROM on my phone.

**Comment by warren-bank** [comment]
Is your [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) fairly recent?

..I mean, it looks like the javascript on the page is crashing the component. Maybe it's just really old and needs an update?

**Comment by sagorahmed** [comment]
Oh god! my phone's Android system Webview was updated a long time ago. Now it is not occurring.
Thanks for encountering the main issue! :)

**Comment by warren-bank** [comment]
I'm glad for you that's all it was.. easy fixes are always the best fixes. :)

**Comment by sagorahmed** [comment]
Is it possible to inform the users about the outdated Android system Webview from this app??

**Comment by warren-bank** [comment]
The README already has a [section](https://github.com/warren-bank/Android-WebCast#status) about that topic.

Personally, I feel that serves as enough of a warning. I don't think an app should nag the user to upgrade external dependencies.. I'd find that very annoying.

Plus, there's the whole issue that the WebView ecosystem is inconsistent. Android 4.x is stuck with whatever was baked into their OS. Android 5-7 can upgrade. Android 7+ defaults to using Chrome (if it's installed).. and falling back to the upgradable system WebView if it isn't.. plus they can install alternate WebViews and choose which one to use as default under _developer settings_. It's a mess.. and ultimately it boils down to each Android user/owner being responsible for maintaining/upgrading their own system in whatever way they like best.

**Comment by sagorahmed** [comment]
Hmm, I got it.
It's been a pleasure to talk with you. I learned something new from you. Thanks!
