### ISSUE TITLE
externally viewing to download the video

### ISSUE THREAD

**Issue by Mobius90** [warren-bank/Android-WebCast#3]
ill ask the question here so the app catches the link i pressed the view with external player then i picked the download manager and it worked fine now the problem is when i manually take the link from the videos tab and put it in download manager it doesnt work is it like a token type of link 
can we chat on discord pls m1ke#5850

**Comment by warren-bank** [comment]
example?

* which external download manager app are you using
* URL to webpage (containing video)

I could understand a video playing internally, but not externally. Internally the app sets _Referer_ and _Origin_ request headers that an external app (other than _ExoAirPlayer_) wouldn't. But if you're comparing starting an Intent (with a video URL in its _data_) to manually copy/pasting the exact same video URL into the exact same external app.. I'd expect the same result. Having said that, the Intent does also forward the mime-type of the video.. but I'd expect a download manager to be able to obtain that from the _Content-Type_ response header. The only other possibility (that I can think of off-hand) is that the video URL is only valid for a brief lifespan and quickly expires. So.. an example would be helpful.

Have you experimented with requesting this example video URL on the command-line with curl? What does the server say?

**Comment by warren-bank** [comment]
PS: I fkn __love__ the app: [Intent Intercept](https://f-droid.org/en/packages/de.k3b.android.intentintercept/)
* to inspect fields
* to copy data from fields
* to modify fields, and then start a new Intent
