### ISSUE TITLE
player

### ISSUE THREAD

**Issue by BreynerStand** [warren-bank/Android-WebCast#4]
Any way to open the player without having to wait for the whole process to load the page?

**Comment by warren-bank** [comment]
The app allows you to (internally) save bookmarks for video URLs.. so you can rewatch them again later. Of course, this will only work if the video URL itself doesn't expire (ie: the video server will only serve the stream while the link is valid).

It also has an Intent filter to be able to use the internal ExoPlayer video player to play (and cast) video URLs that are shared from other apps. For example, this would allow to save video URL bookmarks in an external app, and watch them in this app (or any other video player app with an appropriate Intent filter).
