### ISSUE TITLE
Unable to cast YouTube videos

### ISSUE THREAD

**Issue by rajBopche** [warren-bank/Android-WebCast#5]
I am able to cast the videos on my TV from abcNews very well. But it does not work for any of the YouTube videos.
In fact when the YouTube videos are searched they don't list on the left side drawer in the same manner as abcVideos did?

### See how the left drawer contains the video listing available on abcnews site

![Screenshot_2021-03-10-14-25-39-296_com github warren_bank webcast](https://user-images.githubusercontent.com/42612104/110603566-27ae6d00-81ad-11eb-90c2-4b8abef8e9b7.jpg)

### However in case of YouTube the video listing section is completely empty

![Screenshot_2021-03-10-14-29-07-726_com github warren_bank webcast](https://user-images.githubusercontent.com/42612104/110603559-25e4a980-81ad-11eb-99a5-6b55f8ce0ca5.jpg)

**Comment by warren-bank** [comment]
Not an error with the application; the video player on the Youtube website does a good job masking its network traffic such that the application is unable to detect its video stream(s). Site-specific logic would be needed. A greasemonkey userscript would be better suited for that task.

**Comment by warren-bank** [comment]
If you feel like a homework assignment..

* [here](https://github.com/warren-bank/crx-Youtube/blob/greasemonkey-userscript/greasemonkey-userscript/Youtube.user.js) is a greasemonkey userscript that I wrote to run in desktop Chrome to extract URLs to mp4 video files from Youtube
* [here](https://github.com/warren-bank/Android-WebMonkey) is another Android application that I wrote to run greasemonkey userscripts on Android
  - it has some additional APIs that are specifically for use with Android
  - one such API can pass the URL of an mp4 video file to another application via an Intent
    * any of your video players would be able to play the video file
    * WebCast can accept this Intent and play the video as though it had been extracted from the website directly, and its internal video player can then cast the URL of the mp4 video to a Chromecast device
* [here](https://warren-bank.github.io/Android-WebMonkey/) is a collection of greasemonkey userscripts that I've already ported over from desktop to Android, and follow this methodology to extract a video from a website and hand it over to another video player via Intent
  - disclaimer: this is a game of cat-and-mouse; the target websites are constantly being updated, which cause the userscripts to stop working until also updated..

If you feel like it, you're welcome to port the [Youtube userscript](https://github.com/warren-bank/crx-Youtube) from desktop to Android. It wouldn't need any code to modify DOM.. only code to find and forward the video URL.

**Comment by rajBopche** [comment]
Kudos to quick response, haven't really worked with greaseMonkey but surely looks interesting.

**Comment by warren-bank** [comment]
At the moment, I'm pretty focused on something else.. but at some point I'll circle around to looking at this. It shouldn't be too difficult. I didn't originally bother to port that script since YT's video player has a Chromecast sender already built it.

However, dealing directly with the mp4 video file URL has benefits:
* if the Intent is used to start a video player, then there are no commercials added to the stream
* the Intent could be used to start a file download manager.. to save the video to external storage (to watch offline)

**Comment by rajBopche** [comment]
Ended up running Python on Android to extract the actual YT's downloadable url.

After setting up [Chaquopy](https://chaquo.com/chaquopy/doc/current/android.html) and then importing [PyTube](https://github.com/pytube/pytube) on Android all I needed was this line.

```java
py.getModule("pytube").callAttr("YouTube",
            "https://www.youtube.com/watch?v=FT6XaOrZhsA").get("streams").asList().get(0).get("url").toString()
```

_Note: Python Object Instantiation on Android was terribly slow. Use threads._
