### ISSUE TITLE
Asked assistant

### ISSUE THREAD

**Issue by AdnanGo1** [warren-bank/Android-WebCast#8]
Peace be upon you, brother. I want you to create a library that converts indirect links into direct links, because I want to make an application to watch anime, and I really need this feature.

I hope you reply me quickly

**Comment by warren-bank** [comment]
Please explain what you mean by: "converts indirect links into direct links"

Actually.. a complete example (from input to desired output) would be the best way to explain..

**Comment by AdnanGo1** [comment]
I want to extract video stream link from links.
Like: https://ssbstream.net/e/9nqkan6d9r4d

There is a library called Xgetter that does this but it is not good at converting all links

And your Webcast Project is good at converting links to video streams, but it converts links to video streams until I play one of the videos in the browser and it appears in the side menu to the right of it. The video stream link is its own, I would just like it to take a text with a link that turns it into a video stream link, instead of playing a video in a browser

**Comment by warren-bank** [comment]
so basically you want to:
* accept a URL to a page on a video hosting site.. that displays a video player for a given video
* output the URL for the raw video stream

thoughts:
1. not hard to do..
2. you need to disect the website and understand how its page is loading the video
   * possibly following a few XHR requests and parsing some JSON
3. write a tool to do the same thing.. in a streamlined fashion
4. update your tool every time the website makes a change that breaks this methodology
5. ..outside the scope of this project
   * a Greasemonkey script is a good choice to implement this kind of behavior
