### ISSUE TITLE
Asked assistant

### ISSUE THREAD

**Issue by AdnanGo1** [warren-bank/Android-WebCast#9]
I accidentally deleted my message to you.

**Comment by AdnanGo1** [comment]
Well, brother, I will see the way that you told me, but if it is better for me to communicate with you via WhatsApp or Telegram in case I have a problem, this is my number +212618144535

**Comment by AdnanGo1** [comment]
Or update your project across the web and add the feature to convert a link into a video stream link. This will help me a lot bro, and I'm sorry if I bothered you

**Comment by warren-bank** [comment]
I had closed [the issue](https://github.com/warren-bank/Android-WebCast/issues/8) as off-topic.

This app obtains its video links by inspecting HTTP requests as the page loads.
Your request is to apply site-specific knowledge to obtain video links without page loading.
Unrelated.. and my closing comment in your original issue gave suggestions for how you would do so.

Not my job to do it for you.. and if you don't know how.. hire someone (else).
Good luck in your endeavour.

**Comment by warren-bank** [comment]
PS: I would close this duplicate issue now, but I'm concerned that you wouldn't be able to find it any longer. Please close this issue after you've read the comments. Thanks.

**Comment by AdnanGo1** [comment]
Ok bro
